### ISSUE TITLE
Token auto-renewal does not update token in active conversations

### ISSUE THREAD

**Issue by 0x530302** [wireapp/lithium#15]
The token auto-renewal that is used when running in user mode, requests a new token every 15 minutes and thereby also invalidates the previous token. This token is then stored as a member of the Endpoint class (c.f., [Endpoint.java:L179](https://github.com/wireapp/lithium/blob/develop/src/main/java/com/wire/bots/sdk/user/Endpoint.java#L179)). However, existing clients (i.e., the API class) only receive the token on construction, which prevents any posting of messages after the first renewal.

My current workaround is changing the token variable in `Endpoint` to static and modifying the `bearer()` function to directly access the static token of Endpoint:
```diff
diff --git a/src/main/java/com/wire/bots/sdk/user/API.java b/src/main/java/com/wire/bots/sdk/user/API.java
index 90dbd99..eadf20c 100644
--- a/src/main/java/com/wire/bots/sdk/user/API.java
+++ b/src/main/java/com/wire/bots/sdk/user/API.java
@@ -202,7 +202,7 @@ public class API extends LoginClient {
     }
 
     private static String bearer(String token) {
-        return "Bearer " + token;
+        return "Bearer " + Endpoint.getToken();
     }
 
     Conversation getConversation() throws IOException {
diff --git a/src/main/java/com/wire/bots/sdk/user/Endpoint.java b/src/main/java/com/wire/bots/sdk/user/Endpoint.java
index 09d782e..3290536 100644
--- a/src/main/java/com/wire/bots/sdk/user/Endpoint.java
+++ b/src/main/java/com/wire/bots/sdk/user/Endpoint.java
@@ -56,7 +56,7 @@ public class Endpoint {
     private final CryptoFactory cryptoFactory;
     private UserMessageResource userMessageResource;
     private ClientManager client = null;
-    private String token;
+    private static String token;
     private String cookie;
     private String clientId;
     private String botId;
@@ -186,7 +186,7 @@ public class Endpoint {
         }, TimeUnit.MINUTES.toMillis(periodMinutes), TimeUnit.MINUTES.toMillis(periodMinutes));
     }
 
-    public String getToken() {
+    public static String getToken() {
         return token;
     }
```

A less hacky solution might be to pass an `Endpoint` reference to `API` and query the token every time it is required?

Thanks!

**Comment by dkovacevic** [comment]
Hi. Thanks for reporting!
It;s been a while since I used Endpoint or whole User Mode. But now I need it also. Will fix this today/tomorrow!

**Comment by dkovacevic** [comment]
OK. I think I have something already. First a quick disclaimer:
Lithium SDK was designed to implemented Wire Bot API that has end-to-end encryption, protobufs, tons of authorization and more...
UserMode was put there in order to allow devs who, for some reason, cannot or don't want to use the BotMode (usually they don't have a public IP with TLS termination)
Some differences between these two modes:
`UserMode` vs. `BotMode`
- `Web sockets` vs `Web hooks`
- Single `Cryptobox` vs One `Cryptobox` per _each_ bot instance
- One `access token` with 15min life span vs One `access token` per each bot instances with lifelong span
Users can send connect requests vs Bots need to be placed into convs by the user

UserMode design:
- `Endpoint`t class: Obtains access token using email/password and renewal of it. Opens and keeps websocket alive. Inbound messages come through these websockets
- `UserClient` class: primary client object for talking to Wire Backend. Outbound traffic. Short lived object. Use it and forget it. Don't cache it! Allows you to post messages only into dedicated conv.
- `UserClientRepo` class: factory of `UserClient`s. Opens Crypto box, fetches the State from the storage.
- `MessageHandlerBase` abstract class: Handles inbound messages ;). Override methods that you need. Put your business logic into those overrides. Each method has UserClient and Message params. Use this client to _reply_ to _message_

Access token is renewed every 15 minutes and persisted to Storage. Each new inbound message will trigger UserClient object creation that will pull the fresh State.
